# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9765b19e23ba38724cab5dc65bffe72e3a1c1c1e264d6d254dd37531e4fc4772911cc8b4e9057623714d465d08ddc630e8351b8c4521d9436f0f71e8c56d5b71

test:
  secret_key_base: 6026079a81f07fe5e11e7afd2517eab02da27e1251c40471d1cd49b6b47c11b181be79bc8e11a2adfadf0a2f85d01296fd2dd2f6e06a574d1658bc392ad98ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
